PREFIX prism: <https://prismdb.takanakahiko.me/prism-schema.ttl#>

SELECT concat("\n;; okuri-ari entries.\n;; okuri-nasi entries.\n\n",
group_concat(concat(replace(?skana, " ", ""), " /", replace(?sname, " ", ""), ";[prismdb] ", ?sclass, "/"); separator="\n"),
"\n")
WHERE {
    ?s a prism:Team;
        prism:name ?sname;
        prism:name_kana ?skana;
        a/rdfs:label ?sclass.
    bind("" as ?g)
}
group by ?g

