name: re-generate

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: master

jobs:
  re-generate:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install nkf
    - run: sh gen.sh
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🤖 Automatically update SKK-JISYO"
        author: banjun <banjun@gmail.com>
        title: 'Update the generated SKK-JISYO'
        body: |
            Automatically update SKK-JISYO
        branch: re-generate-skk-jisyo
