name: re-generate

on:
  schedule:
    - cron: '25 * * * *'

jobs:
  re-generate:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: sh gen.sh
    - uses: gr2m/create-or-update-pull-request-action@v1.x
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
